language: node_js
node_js:
  - lts/*
script: yarn test --coverage
before_deploy: yarn build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: setup_ci